### ISSUE TITLE
Support <exclude>findbugs:org.package.Class:method:RuleName</exclude>

### ISSUE THREAD

**Issue by ilyakharlamov** [yegor256/qulice#1020]
Currently, findbugs allows excluding the files only on a per-class basis, using the `pom.xml` syntax
`<exclude>findbugs:org.package.Class</exclude>`
However that excludes all the methods and all the rules.

The proposal is to extend the syntax using colon syntax (somewhat similar to [IPv6 multicast addresses](https://en.wikipedia.org/wiki/IPv6_address#Multicast_addresses)):
`<exclude>findbugs:org.package.Class</exclude>` - exclude the whole class, all rules
`<exclude>findbugs:org.package.Class:method</exclude>` - exclude the metod, all rules
`<exclude>findbugs:org.package.Class:method:RuleName</exclude>` - exclude the specific rule for specific method
`<exclude>findbugs:org.package.Class::RuleName</exclude>` - Exclude the rule for the whole class
`<exclude>findbugs:::RuleName</exclude>` - Exclude specific rule for all the classes

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/1020#issuecomment-459359832))

@krzyk Job [#1020](https://github.com/teamed/qulice/issues/1020) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by krzyk** [comment]
@0crat assign @ilyakharlamov

**Comment by 0crat** [comment]
> @0crat assign @ilyakharlamov  ([here](https://github.com/teamed/qulice/issues/1020#issuecomment-459371434))

@krzyk The job [#1020](https://github.com/teamed/qulice/issues/1020) assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C3T49A35L/2d465861-fe90-49b0-a91c-d3049b0241be); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by llorllale** [comment]
@ilyakharlamov @krzyk where are we on this?

**Comment by ilyakharlamov** [comment]
There is a PR #1023 that implements that, what else can I do.

**Comment by yegor256** [comment]
@ilyakharlamov we don't have findbugs here anymore
