### ISSUE TITLE
build fails if XCOP is installed

### ISSUE THREAD

**Issue by ilyakharlamov** [yegor256/qulice#1021]
Steps to reproduce:

1. Start with a fresh environment, for example docker or [gitpod](https://gitpod.io/#https://github.com/teamed/qulice)
2. Checkout a recent qulice src something like `git checkout 7dc06ee6463b921b98f2de9528c1ea74d7666a02`
3. type `gem install xcop` to the console
4. `mvn install`

What's wrong:
if xcop is not in the PATH, everything is fine
however if xcop is avaliable, then build fails:
```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project qulice: An Ant BuildException has occured: exec returned: 255
[ERROR] around Ant part ...<exec failonerror="true" executable="xcop">... @ 18:50 in /workspace/qulice/target/antrun/build-main.xml
```

Expected result:
The build should not fail because of the presence of external tools

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@ilyakharlamov this should be solved with https://github.com/teamed/qulice/issues/1017, we migrated to new parent but we didn't fix the xml files formatting, so for now xcop shouldn't be used until we finish it
