### ISSUE TITLE
Update maven-compiler-plugin and fix bug on it to allow incremental compilation 

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/qulice#1039]
Let's update `maven-compiler-plugin` to 3.8.0 version and fix a bug in this plugin which doesn't allow incremental compilation that increase compile and running time. To fix both we need change `pom.xml` to:
```
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.0</version>
  <configuration>
    <source>1.8</source>
    <target>1.8</target>
    <useIncrementalCompilation>false</useIncrementalCompilation>
  </configuration>
</plugin>
```
Please, pay attention to `<version>` and `<useIncrementalCompilation>` tag.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by fabriciofx** [comment]
@krzyk ping

**Comment by fabriciofx** [comment]
@krzyk ping

**Comment by yegor256** [comment]
@fabriciofx this is fixed already, I believe
