### ISSUE TITLE
CLI support for Qulice

### ISSUE THREAD

**Issue by mronus** [yegor256/qulice#1050]
I am not sure if Qulice has CLI. I couldn't find anything except maven support in docs. What I want to do is that I want to run Qulice for a specific folder or set of files by using a specific static analysis tool supported by Qulice. Does Qulice have CLI support?

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@mronus[/z](https://www.0crat.com/u/mronus) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@mronus we don't support this now, but you can do it with a simple `pom.xml`.
