### ISSUE TITLE
Can we disable AvoidInlineConditionals

### ISSUE THREAD

**Issue by golszewski86** [yegor256/qulice#1054]
The Checkstyle _AvoidInlineConditionalsCheck_ rule forbids usage of ternary operator `?`. There is however very little justification for that, Checkstyle documentation only says:
> Some developers find inline conditionals hard to read, so their employer's coding standards forbid them.
(http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheck.html)

It is not clear to me what does "some developers" mean, however word "some" suggests it is a minority of developers.
It is also not explained why inline conditional is "hard to read". For me they are pretty easy to read.

Can we get rid of this rule?

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@golszewski86 ternary operators make code harder to read. Such a check is very common for style checkers in other languages too. So, we keep it.

**Comment by golszewski86** [comment]
y'all insane lmao if you find inline conditionals hard to read go back to school
