### ISSUE TITLE
RegexpSinglelineCheck applies to *.png, *.js, *.css files within the standalone application

### ISSUE THREAD

**Issue by dgroup** [yegor256/qulice#1055]
```
....
[INFO] --- qulice-maven-plugin:0.18.19:check (apply-qulice-validations) @ app ---
[INFO] Checkstyle: app/src/main/resources/css/images/arrow_undo.png[7]: Line has trailing spaces. (RegexpSinglelineCheck)
[INFO] Checkstyle: app/src/main/resources/css/images/row-over-bg.gif[1]: Line has trailing spaces. (RegexpSinglelineCheck)
[INFO] Checkstyle: app/src/main/resources/css/images/row-over-bg.gif[4]: Line has trailing spaces. (RegexpSinglelineCheck)
[INFO] Checkstyle: app/src/main/resources/css/images/ajax-loader-small.gif[1]: Line has trailing spaces. (RegexpSinglelineCheck)
[INFO] Checkstyle: app/src/main/resources/css/images/ajax-loader-small.gif[3]: Line has trailing spaces. (RegexpSinglelineCheck)
[INFO] Checkstyle: app/src/main/resources/css/images/ajax-loader-small.gif[6]: Line has trailing spaces. (RegexpSinglelineCheck)
...
[INFO] Checkstyle: app/src/main/resources/css/d8028d77a21b72097d41c29284210d534de247fe.cache.css[204]: This kind of comment is not allowed. (RegexpSinglelineCheck)
[INFO] Checkstyle: app/src/main/resources/css/d8028d77a21b72097d41c29284210d534de247fe.cache.css[213]: This kind of comment is not allowed. (RegexpSinglelineCheck)
[INFO] Checkstyle: app/src/main/resources/css/d8028d77a21b72097d41c29284210d534de247fe.cache.css[235]: This kind of comment is not allowed. (RegexpSinglelineCheck)
```
https://checkstyle.sourceforge.io/config_regexp.html#RegexpSingleline

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by dgroup** [comment]
@krzyk up

**Comment by dgroup** [comment]
@paulodamaso @krzyk Is there any chance to fix this issue?
Today I found that this rule is applying to `*.class` files which are available in `/src/test/resources`.
I'm writing a lib that manipulates with bytecode and can't use qulice due to this rule :(.

I don't want to invent different hacks in order to avoid this violation... :(

**Comment by dgroup** [comment]
@paulodamaso the pull request also available, we can define white list or blacklist with extensions....

**Comment by pnatashap** [comment]
@yegor256 @dgroup issue can be closed, rule should be applied to java files only 
https://github.com/yegor256/qulice/blob/c0a3d55e5cb553c5afe4121ca42f234a2c7c3e7d/qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml#L80-84
