### ISSUE TITLE
Consistency to consider capital letter

### ISSUE THREAD

**Issue by HDouss** [yegor256/qulice#1070]
In Qulice 0.18.19, If I have this code:
```java
    /**
     * constructor.
     * @param add {@link FieldAddition}
     * @param mul Field multiplication
     */
    public AbstractField(final FieldAddition<T> add,
        final FieldMultiplication<T> mul) {
        this.add = add;
        this.mult = mul;
    }
```
Qulice will complain with 2 violations:
* `First sentence in a comment should start with a capital letter (RegexpMultilineCheck)` because "constructor" starts with a lowercase letter
* `@param tag description should start with capital letter (RegexpSinglelineCheck)` because param add starts with a javadoc link

If I replace "constructor" with a javadoc link, for example:
```java
    /**
     * {@link FieldAddition}.
     * @param add {@link FieldAddition}
     * @param mul Field multiplication
     */
```
Qulice will not complain anymore for the first sentence in the comment. So making a javadoc link is fine for qulice as a capital letter starting, if it is in the comment, but not in the param tag description.

We should have consistency whether to consider a javadoc link a starting capital letter or not.
The better option is to consider it as a starting capital letter in all cases (so even as a `@param`/`@return` tag description), having links in javadoc is often handy.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@hdouss[/z](https://www.0crat.com/u/hdouss) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by HDouss** [comment]
@krzyk ping

**Comment by yegor256** [comment]
@HDouss this is coming from Checkstyle, we won't/can't fix this
