### ISSUE TITLE
MultilineJavadocTagsCheck in package-info.java

### ISSUE THREAD

**Issue by HDouss** [yegor256/qulice#1072]
MultilineJavadocTagsCheck is forcing to have a one-space indentation for javadoc tags that span into multiple lines (for example @todo puzzles tags). However, this check is not done for package-info.java files. Sometimes it is useful to make a puzzle concerning a whole package and the most suitable place to put it is the `package-info.java` file. It would be nice to make this check especially that pdd gem is doing this check and makes rultor merge scripts to fail.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@hdouss[/z](https://www.0crat.com/u/hdouss) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
