### ISSUE TITLE
JavadocMethodCheck for @Test methods should be suppresed

### ISSUE THREAD

**Issue by andreoss** [yegor256/qulice#1075]
`JavadocMethodCheck` should be disabled for test methods
- It's very common to disable this check
  For example 93% of `cactoos` tests contains suppression of this check
- It's redundant, usually methods body will contain an assertion with a description similar to javadoc
  `Matchers.assertThat("same as in javadoc", ....)`
- It's applied only for Junit 4
  Junit 5 does not require `public` modifier, so the rule is not applied

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by pnatashap** [comment]
@yegor256 may be close this one? It looks like now it is better to migrate to JUnit5 instead of making exclusions.

**Comment by yegor256** [comment]
@andreoss indeed, we won't fix this. Just migrate to JUnit5.
