### ISSUE TITLE
Could the license be checked with RegexpHeader instead of Header?

### ISSUE THREAD

**Issue by StuporHero** [yegor256/qulice#1080]
Checkstyle is [currently configured](https://github.com/teamed/qulice/blob/90c29bcf4ab7f671dd24f909892cca2bb6f247c3/qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml#L154) to use [Header](https://checkstyle.sourceforge.io/config_header.html#Header) to check the copyright/license notice in source files. Could that be changed to [RegexpHeader](https://checkstyle.sourceforge.io/config_header.html#RegexpHeader)? I ask because I'm creating a derivative work of a project that uses the MIT License, and I want to preserve the original copyright/license headers in the original source files of that project but want to only include the copyright and license notice for the derivative work in new files that I write. Regexp would allow me to do that.

**Comment by yegor256** [comment]
@StuporHero we are not planning to do this. Keep the code that doesn't belong to you in special directories and disable Qulice for them.
