### ISSUE TITLE
Update Copyright notice to 2021

### ISSUE THREAD

**Issue by AlexElin** [yegor256/qulice#1085]
Copyright notice should be updated to 2020

**Comment by andreoss** [comment]
There is no need to update the notice. 
No copyrightable changes were made in 2020. 

https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

**Comment by AlexElin** [comment]
I think there's need because currently all CI builds would fail.
A check for a year in copyright is performed by [years.sh](https://github.com/teamed/qulice/blob/master/years.sh).
Additionally there were similar changes earier: issue https://github.com/teamed/qulice/issues/977 and PR https://github.com/teamed/qulice/pull/997
