### ISSUE TITLE
Qulice does not handle module-info

### ISSUE THREAD

**Issue by andreoss** [yegor256/qulice#1096]
Qulice falsely detects `module-info` files in different modules as a duplicate:

```
20:45:29,606 [INFO] --- qulice-maven-plugin:0.18.19:check (jcabi-qulice-check) @ jcabi-jdbc ---
Sep 21, 2021 8:45:33 PM net.sourceforge.pmd.lang.ast.xpath.Attribute getValue
WARNING: Use of deprecated attribute 'FieldDeclaration/@VariableName' in XPath query
20:45:39,955 [INFO] Starting FindBugs validator
20:45:39,955 [INFO] Finishing FindBugs validator
20:45:40,161 [INFO] Calling org.apache.maven.plugins:maven-enforcer-plugin:1.0-beta-1:enforce...
20:45:40,237 [INFO] Calling com.ning.maven.plugins:maven-duplicate-finder-plugin:1.0.7:check...
20:45:40,240 [INFO] Checking compile classpath
20:45:40,482 [WARNING] Found duplicate and different classes in [com.fasterxml:classmate:1.5.1,org.projectlombok:lombok:1.18.20] :
20:45:40,482 [WARNING]   module-info
```

Related to https://github.com/basepom/duplicate-finder-maven-plugin/issues/31

**Comment by yegor256** [comment]
@andreoss do you know how this can be fixed?

**Comment by jvb** [comment]
`      <plugin>
         <groupId>org.basepom.maven</groupId>
         <artifactId>duplicate-finder-maven-plugin</artifactId>
           <configuration>
              <ignoredClassPatterns>
                <ignoredClassPattern>.*module-info$</ignoredClassPattern>
              </ignoredClassPatterns>
             </configuration>
`

**Comment by yegor256** [comment]
@andreoss Duplicated of #1077
