### ISSUE TITLE
Unable to configure suppression of specific Checkstyle checks for particular package in maven plugin

### ISSUE THREAD

**Issue by mximp** [yegor256/qulice#1109]
I want to ignore specific check for all java files in specific package:
```
[INFO] Checkstyle: src/main/java/EOorg/EOeolang/EOstring$EOslice.java[42]: Name 'EOstring$EOslice' must match pattern '^[A-Z][a-zA-Z0-9]*$'. (TypeNameCheck)
```

Checkstyle plugin has configuration mechanism for that (`suppressionsLocation`property).

Is there similar approach in Qulice?

**Comment by mximp** [comment]
@yegor256 shall we consider implementing this?

**Comment by yegor256** [comment]
@mximp nope, this is against the philosophy of Qulice. It's a non-configurable tool.
