### ISSUE TITLE
to add JUnit5TestShouldBePackagePrivate to qulice pmd ruleset

### ISSUE THREAD

**Issue by Graur** [yegor256/qulice#1130]
Related to this: https://github.com/objectionary/eo/issues/1035

We need to add a new PMD check to qulice pmd ruleset: `JUnit5TestShouldBePackagePrivate`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.0`

**Comment by yegor256** [comment]
@Graur thanks!!
