### ISSUE TITLE
method parameter must not hide field of the class

### ISSUE THREAD

**Issue by yegor256** [yegor256/qulice#1161]
This code must lead to a complaint:

```
class Foo {
  private String test = "";
  void bar(String test) { // error is here
    System.out.println("Hello: " + test);
  } 
}
```

Because the name `test` hides the name of the existing attribute `this.test`.

**Comment by MikailBag** [comment]
Isn't such code covered by https://checkstyle.org/checks/coding/hiddenfield.html#HiddenField?

Diff: https://github.com/MikailBag/qulice/actions/runs/6909008992/job/18799497077?pr=5#step:5:2614

Outcome: https://github.com/MikailBag/qulice/actions/runs/6909008992/job/18799497077?pr=5#step:5:2614
