### ISSUE TITLE
Rebuild GitHub Pages 

### ISSUE THREAD

**Issue by timur-harin** [yegor256/qulice#1196]
@yegor256 

As I see last gihub Pages deployment was 2 years ago, so copyright years in the website is too old
<img width="285" alt="Screenshot 2024-03-05 at 20 50 35" src="https://github.com/yegor256/qulice/assets/64702874/4bd21999-eeec-44aa-b839-7c172910bd91">

And another problem that after your update of logo weblink now is unavailable, because of not updated hosting page https://www.qulice.com/logo.svg
<img width="269" alt="Screenshot 2024-03-05 at 20 54 12" src="https://github.com/yegor256/qulice/assets/64702874/4f440ec5-9c8b-4714-8f53-bb73c17a07b8">
<img width="406" alt="Screenshot 2024-03-05 at 20 54 07" src="https://github.com/yegor256/qulice/assets/64702874/cefc6085-077a-4d04-86fd-7df924fe2e8f">

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`

**Comment by timur-harin** [comment]
Yes, now all is right
