### ISSUE TITLE
PMD.AvoidAccessToStaticMembersViaThis check works incorrectly

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/qulice#1197]
I have the following Java code in [HasMethod.java](https://github.com/objectionary/jeo-maven-plugin/blob/ba7c181ef138a013546f1e328f59821b7d569794/src/test/java/org/eolang/jeo/representation/directives/HasMethod.java#L103):
```java
@Override
public boolean matchesSafely(final String item) {
    final XMLDocument document = new XMLDocument(item);
    return this.checks().stream().map(document::xpath).noneMatch(List::isEmpty); // 113 line is here
}
```

When I run `mvn qulice:check -Pqulice` with version `0.22.1`, I'm getting the following error:
```shell
[INFO] PMD: src/test/java/org/eolang/jeo/representation/directives/HasMethod.java[113-113]: Static members should be accessed in a static way [CLASS_NAME.FIELD_NAME], not via instance reference. (AvoidAccessToStaticMembersViaThis)
```

It's rather strange because the `checks()` is an instance method, not a static member:
```java
/**
 * Checks.
 * @return List of XPaths to check.
 */
private List<String> checks() {
    return Stream.concat(
        Stream.concat(
            this.definition(),
            this.parameters()
        ),
        Stream.concat(
            this.trycatch(),
            Stream.concat(
                this.instructions(),
                this.labels()
            )
        )
    ).collect(Collectors.toList());
}
```

I've tried to find the description of the `AvoidAccessToStaticMembersViaThis` check in PMD and failed. Maybe this check somehow related to `qulice`?

**Comment by volodya-lombrozo** [comment]
BTW, using `@SuppressWarnings("PMD.AvoidAccessToStaticMembersViaThis")` helps to avoid the `qulice` complaint.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by k3p7i3** [comment]
@volodya-lombrozo it seems i found the cause of the problem - in the end of [HasMethod.java](https://github.com/objectionary/jeo-maven-plugin/blob/ba7c181ef138a013546f1e328f59821b7d569794/src/test/java/org/eolang/jeo/representation/directives/HasMethod.java#L420) there is a nested static class with `static Stream<String> checks()` method, and qulice take into account all method declarations named as `checks()`. I'll see what i can do about it.
```
    private static final class HasLabel {

        /**
         * Checks of label.
         * @param root Root Method XPath.
         * @return List of XPaths to check.
         */
        static Stream<String> checks(final String root) {
            return Stream.of(
                String.format(
                    "%s/o[@base='seq']/o[@base='tuple']/o[@base='label' and @data='bytes']/@data",
                    root
                )
            );
        }
    }
```

**Comment by pnatashap** [comment]
Rule AvoidAccessToStaticMembersViaThis get all methods from the file, not from the class body. It is the reason for bug. 
Will ask in pmd how to avoid warning messages and will fix the rule to get only current class methods
