### ISSUE TITLE
DefaultValidatorsProvider.java:47-47: When it works, add {@code...

### ISSUE THREAD

**Issue by davvd** [yegor256/qulice#123]
Puzzle `83-6c3a2ab9` in `src/main/java/com/qulice/maven/DefaultValidatorsProvider.java:47-47` has to be resolved: When it works, add {@code DependenciesValidator()} to this list

**Comment by davvd** [comment]
the last puzzle `123-3eeb54ce`/#349 solved

**Comment by 0pdd** [comment]
@davvd 5 puzzles [#816](https://github.com/teamed/qulice/issues/816), [#817](https://github.com/teamed/qulice/issues/817), [#818](https://github.com/teamed/qulice/issues/818), [#819](https://github.com/teamed/qulice/issues/819), [#949](https://github.com/teamed/qulice/issues/949) are still not solved; solved: [#unknown]().

**Comment by 0pdd** [comment]
@davvd 4 puzzles [#816](https://github.com/teamed/qulice/issues/816), [#817](https://github.com/teamed/qulice/issues/817), [#818](https://github.com/teamed/qulice/issues/818), [#819](https://github.com/teamed/qulice/issues/819) are still not solved; solved: [#949](https://github.com/teamed/qulice/issues/949), [#unknown]().

**Comment by 0pdd** [comment]
@davvd all 4 puzzles are solved here: [#1119](https://github.com/yegor256/qulice/issues/1119), [#1120](https://github.com/yegor256/qulice/issues/1120), [#1121](https://github.com/yegor256/qulice/issues/1121), [#1122](https://github.com/yegor256/qulice/issues/1122).
