### ISSUE TITLE
add a rule to check that affirm is used for Assertion

### ISSUE THREAD

**Issue by pnatashap** [yegor256/qulice#1238]
In case of using org.llorllale.cactoos.matchers.Assertion<>() affirm method should be called to perform validation.

```java
new Assertion<>(
            "toArray() must be equals to original",
            new Immutable<>(
                new ListOf<>(1, 2)
            ).toArray(),
            new IsEqual<>(
                new ListOf<>(1, 2).toArray()
            )
        ).affirm(); // is good
```

```
new Assertion<>(
            "toArray() must be equals to original",
            new Immutable<>(
                new ListOf<>(1, 2)
            ).toArray(),
            new IsEqual<>(
                new ListOf<>(1, 2).toArray()
            )
        ); // error should be displayed, affirm is needed
```

**Comment by IlyaPechersky** [comment]
@pnatashap can you please assign this issue to me?

**Comment by pnatashap** [comment]
@IlyaPechersky I do not have permissions to assign issues, you can ask Yegor or just create a PR. 
Fill free to ping me for review

**Comment by IlyaPechersky** [comment]
@pnatashap, I looked at different options, but I don’t see a suitable one. Can you please suggest me which [AST](https://github.com/pmd/pmd/tree/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast) class is best to use to describe org.llorllale.cactoos.matchers.Assertion<>()?

**Comment by pnatashap** [comment]
@IlyaPechersky actually you need to create a new rule, so you can check the full list and find something similar https://docs.pmd-code.org/latest/pmd_rules_java.html. For example, XPath rules is easy to write, but it is not so powerfull, some of them are implemented in code.

Example rule with the similar functionality https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/CheckResultSetRule.java

**Comment by pnatashap** [comment]
@yegor256 there are a rules for junit assertions and documentation, so this one looks to be the same (And I write this issue after some code review with this issue). But not a mandatory.

**Comment by yegor256** [comment]
@pnatashap junit seems to be a mandatory part of Java ecosystem, while all other testing libraries are just optional elements of it. I suggest to close this ticket as out of scope.

**Comment by pnatashap** [comment]
so we can close this one then
