### ISSUE TITLE
prohibit private constructors if they are not used in the class

### ISSUE THREAD

**Issue by yegor256** [yegor256/qulice#1258]
This code should be illegal:

```
class Foo {
  String s;
  public Foo(String s) {
    this.s = s;
  }
  private Foo(int x) { // this is wrong!
    // ...
  }
}
```

Instead, this private constructor should be public or protected or package visible.

**Comment by pnatashap** [comment]
@yegor256 are you sure about the example? `this(1);` should call private ctor in this case

**Comment by yegor256** [comment]
@pnatashap you are right, my mistake, I updated the example above

**Comment by vladislav-yevtushenko** [comment]
@yegor256 should it be closed?

**Comment by yegor256** [comment]
@vladislav-yevtushenko yes, thanks!
