### ISSUE TITLE
file exclusions in qulice-findbugs

### ISSUE THREAD

**Issue by yegor256** [yegor256/qulice#149]
Let's enable per-file exclusion (similar to what we have in qulice-checkstyle and qulice-pmd) in qulice-findbugs module.

<hr id='w'>
- ~~`149-fa59b6ee`/#352~~
- ~~`149-29796bc9`/#350~~
- `352-f6cf61e2`/#421 (by Michal Kordas)

**Comment by davvd** [comment]
@yegor256 the last puzzle `352-f6cf61e2`/#421 originated from here solved
