### ISSUE TITLE
ConstantUsageCheck error message is misleading

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/qulice#260]
`ConstantUsageCheck` has the following message if it detects a violation:

``` java
String.format("Constant \"%s\" used only once", name);
```

It's misleading. ConstantUsageCheck actually enforces that a private field be used _at least twice_, so it'll also be triggered for unused constants. Let's re-word it to reflect this behavior or otherwise show an alternative message for unused constants.

**Comment by 0pdd** [comment]
@carlosmiranda the puzzle [#1124](https://github.com/yegor256/qulice/issues/1124) is still not solved.
