### ISSUE TITLE
broken build with JDK8

### ISSUE THREAD

**Issue by caarlos0** [yegor256/qulice#333]
Running `mvn clean install -Pqulice` on project root gives the following error:

```
[ERROR] JSR-303 validator failed to initialize: Unable to instantiate Configuration. (see http://www.jcabi.com/jcabi-aspects/jsr-303.html)
```

Related to #330 

<hr id='w'>
- `333-37771839`/#370 (by Krzysztof Krason)
- `370-69914ea1`/#590 (by Krzysztof Krason)

**Comment by davvd** [comment]
@caarlos0 last 2 puzzles `333-37771839`/#370, `370-69914ea1`/#590 that originated from here were solved
