### ISSUE TITLE
Feature requerst: shellcheck integration

### ISSUE THREAD

**Issue by caarlos0** [yegor256/qulice#406]
Maybe we can integrate shellcheck validations in qulice?

I created a project to be used as a submodule for this, if you want to take a look on how it works: https://github.com/caarlos0/shell-travis-build

What do you think?

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by davvd** [comment]
@caarlos0 thanks for the ticket, your account was topped for 15 mins, payment AP-7GJ06438TW840940F

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I will find someone else, no problem

**Comment by longtimeago** [comment]
@krzyk @yegor256 this is really useful thing

**Comment by yegor256** [comment]
@krzyk even though this sounds like a good idea, I think we should start moving in the opposite direction. instead of adding more and more tools to qulice, we should start removing those that are not Java related. jslint, for example. qulice should be purely Java focused. I think so.

**Comment by caarlos0** [comment]
@yegor256 maybe make qulice easily extensible, so we can have `qulice`, `qulice-jslint`, `quelice-shellcheck` and others...

What do you think?

**Comment by yegor256** [comment]
@caarlos0 I'm afraid, we can easily turn this product into mess, since we're not experts in that tools. We are good with Java, let's stay with Java.. those who need JS/Ruby/Shell/Python/etc will find other tools

**Comment by krzyk** [comment]
@yegor256 OK, but this will leave some of project files in maven projects not validated by qulice only by reviewers.

Unless we add those validations manually to travis/rultor configs, that would be probably the easiest option, and less mess in qulice.

And how to deal with XML in such case, leave it in qulice?

**Comment by caarlos0** [comment]
@yegor256 what I meant was: we make qulice extensible, but not necessarily  extend it. Other people may write those extensions if they want to...

**Comment by yegor256** [comment]
@krzyk hm... good question about XML. maybe we can turn qulice into a standalone command line tool that will contain multiple plugins inside, one per each tool/language. we'll make it in, say, Ruby. and plugins will be like .jar files or shell scripts or JavaScripts. whatever...

**Comment by caarlos0** [comment]
@yegor256 in that case, I recommend Golang, which is easier to distribute (it will be a single binary)
