### ISSUE TITLE
IndentationCheck is wrong for annotaions

### ISSUE THREAD

**Issue by longtimeago** [yegor256/qulice#411]
This code should pass the check (Now it fails):

``` java
@SuppressWarnings(
    {
        "PMD.TooManyMethods",
        "PMD.ExcessiveImports",
        "PMD.AvoidDuplicateLiterals"
    }
)
public final class Test {}
```

```
')' have incorrect indentation level 0, expected level should be 4. (IndentationCheck)
```

This code should fail the check (now it pass):

``` java
@SuppressWarnings(
    {
        "PMD.TooManyMethods",
        "PMD.ExcessiveImports",
        "PMD.AvoidDuplicateLiterals"
    }
    )
public final class Test {}
```

<hr id='w'>

**Comment by davvd** [comment]
@longtimeago I will find a developer for the task soon...

**Comment by davvd** [comment]
@longtimeago thanks for tis bug, I topped your account for 15 mins, transaction `55913385`

**Comment by krzyk** [comment]
@davvd this issue depends on checkstyle/checkstyle#1349 (and checkstyle release after that)

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by mkordas** [comment]
@krzyk I'd like to take this one too

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk thanks, I removed the "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk done. @mkordas the task is yours, please go ahead

**Comment by mkordas** [comment]
@davvd I need more time here, we need to wait for Checkstyle 6.15 being released with the fix

**Comment by davvd** [comment]
> @davvd I need more time here, we need to wait for Checkstyle 6.15 being released with the fix

@mkordas of course, thanks for letting me know, take your time

**Comment by yegor256** [comment]
@longtimeago are you sure this bug is still present? I use it like this, without issues:

```
@SuppressWarnings
    (
        {
            "PMD.TooManyMethods",
            "PMD.ExcessiveImports",
            "PMD.AvoidDuplicateLiterals"
        }
    )
public final class Test {}
```

**Comment by mkordas** [comment]
@yegor256 your version works fine, but the code below fails (and it will pass with Checkstyle 6.15)
```
@SuppressWarnings(
    {
        "PMD.TooManyMethods",
        "PMD.ExcessiveImports",
        "PMD.AvoidDuplicateLiterals"
    }
) // violation
public final class Test {}
```

**Comment by krzyk** [comment]
@mkordas Am I correct that new checkstyle will be released no sooner than about 15 days?

**Comment by mkordas** [comment]
@krzyk yes - I helped to develop the fix for this issue in Checkstyle, but releases are at the end of each month so we need to wait

**Comment by krzyk** [comment]
@mkordas so I would put this one back to postponed and assign to you when the checkstyle is released (I would probably need a ping :) ), unless you prefer to leave it as it is right now

**Comment by mkordas** [comment]
@krzyk yes, that would be perfect

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by krzyk** [comment]
@mkordas new checkstyle has been released, can you take this?

**Comment by mkordas** [comment]
@krzyk sure, I'll take that just after @davvd assigns reviewer to #681

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk there are already 11 active tasks in the project, we can't have more

**Comment by krzyk** [comment]
@davvd could you list the "active tasks", I see only 7 active (3 pull requests and 4 issues).

**Comment by davvd** [comment]
@longtimeago once `411-71c8871e` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by mkordas** [comment]
@krzyk can we unpostpone this so that I can be assigned here finally?

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1128](https://github.com/yegor256/qulice/issues/1128) is still not solved.

**Comment by 0pdd** [comment]
@longtimeago the only puzzle [#1128](https://github.com/yegor256/qulice/issues/1128) is solved here.

**Comment by longtimeago** [comment]
thanks
