### ISSUE TITLE
PDD-049CFC45-11: findbugs validator doesn't work

### ISSUE THREAD

**Issue by yegor256** [yegor256/qulice#60]
_migrated from Trac, where originally posted by **yegor256** on 20-Nov-2011 6:44pm_

Puzzle `PDD-049CFC45-11` should be solved: [source:/trunk/qulice/qulice-maven-plugin/pom.xml@362:191-196]. Findbugs validator doesn't work at the moment. Actually it works, but when finished it crashes JVM. In order to reproduce the problem you should enable it in `ValidatorsProvider` and then validate some other project with qulice. The budget is **1 hour**.

<hr id='w'>
- `60-2649436b`/#388 (by Krzysztof Krason)

**Comment by davvd** [comment]
@yegor256 last puzzled solved `60-2649436b`/#388
