### ISSUE TITLE
Findbugs exclusions doesn't work in the same pattern as others

### ISSUE THREAD

**Issue by caarlos0** [yegor256/qulice#693]
In `pom.xml`, excluding singular files from findbugs like we do for checkstyle, for example, doesn't seem to work:

``` xml
<exclude>findbugs:/src/main/java/com/package/Class.java</exclude>
```

While excluding the entire project does work:

``` xml
<exclude>findbugs:.*</exclude>
```

And excluding singular files in this notation also work:

``` xml
<exclude>findbugs:package.Class</exclude>
```

This is rather confusing.

We could warn/error user if the user uses slashes in the exclude and print an example exclude to show how they should look like.

**Comment by krzyk** [comment]
@caarlos0 see http://www.qulice.com/qulice-maven-plugin/example-exclude.html, the findbugs part

**Comment by caarlos0** [comment]
@krzyk yeah... but I still think we should do something more about it.

For example, we could detect the `/` on the findbugs exclusions and print the link to the user, or maybe convert it automatically to the findbugs notation...

What you do you think?

**Comment by krzyk** [comment]
@caarlos0 it is not much a notation, but a fully qualified name of the class, this class can be in different directories, e.g. in main, or in test. I'm not sure if there is a clean way to convert it.
We could warn/error user if he uses slashes in the exclude and print how example exclude should look like.

**Comment by caarlos0** [comment]
@krzyk works for me

**Comment by krzyk** [comment]
@caarlos0 OK, please update the description with this desired solution.

**Comment by caarlos0** [comment]
@krzyk done

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by davvd** [comment]
@caarlos0 thanks for this report, I added 15 mins to your account, in transaction `56c31dfe53fc490ed5000011`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else
