### ISSUE TITLE
FindBugs needs the project to be re-compiled to update the results

### ISSUE THREAD

**Issue by caarlos0** [yegor256/qulice#694]
If I run `mvn qulice:check`, for example, I will get the list of issues.

Supposing I have one FindBugs issue to fix.

I fix it, and run `mvn qulice:check` again. But the issue still there. It only goes away if I run `mvn clean install qulice:check`.

This workflow works well for PMD and Checkstyle

For findbugs, if latest modification time of `*.java` files is newer then the oldest modification time of `*.class` file, we should "[WARN] Sources need to be recompiled for FindBugs check to work correctly".

**Comment by krzyk** [comment]
@caarlos0 Yes, FindBugs works on compiled classes that's why it need the project to be compiled.
Do you have an idea on which page it should be mentioned?

**Comment by caarlos0** [comment]
@krzyk yeah, I figured that out... 

Maybe in the project README? Or in FAQ? I'm not really sure..

**Comment by krzyk** [comment]
@caarlos0 see http://www.qulice.com/qulice-maven-plugin/example-exclude.html, the findbugs part

**Comment by krzyk** [comment]
@caarlos0 other option that I think of is to compare modification dates of java files and matching class files. If latest modification time of *.java files is newer then the oldest modification time of *.class file it should "[WARN] Sources need to be recompiled for FindBugs check to work correctly"?

**Comment by caarlos0** [comment]
@krzyk Wonderful idea!

**Comment by krzyk** [comment]
@caarlos0 could you update issue description with that?

**Comment by caarlos0** [comment]
@krzyk done

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by davvd** [comment]
@caarlos0 thanks for reporting! I topped your account for 15 mins, transaction 56bde272e626e91318000053

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon
