### ISSUE TITLE
Error description plugin or online service - open discussion.

### ISSUE THREAD

**Issue by rachlenko** [yegor256/qulice#765]
Hello , 
Following our discussion , I just introduce new feature which allow to find the error message in online db and show how to fix the problem.

it could be online service , just synchronized  list of errors with checkstyle and PMD , short description and examples how to fix it.

We also can aggregate statistics from examples with buttons /helps or not / and learn which examples was good, bad, most popular , etc..  

What do you think?

**Comment by yegor256** [comment]
@krzyk what do you think?

**Comment by yegor256** [comment]
@rachlenko project architect is @krzyk, but I also have some say here :)

**Comment by rachlenko** [comment]
@krzyk . I can help to implement it

**Comment by rachlenko** [comment]
yegor256  I believe you could help me with the plugin architecture introduction. I have no experience with IntelliJ plugin writing.

**Comment by krzyk** [comment]
@rachlenko I onestly don't know what this feature request is about. Could you describe it once more?

**Comment by rachlenko** [comment]
@krzyk Well, think any new user like me meet that problem when running  qulice first time.
qulice problem's description sometimes is not clear for less experienced users. Therefore, I've started the discussion about improvements . I think qulice could be more popular if an error message will be found in the well-organized resource with code example and documentation. I am writing about this resource, which we can do . What do you think about?

**Comment by krzyk** [comment]
@rachlenko Wouldn't just http://checkstyle.sourceforge.net/checks.html, https://pmd.github.io/pmd-5.4.1/pmd-java/rules/index.html or http://findbugs.sourceforge.net/bugDescriptions.html be enough.

I know that some of those rules are not described in length (especially FindBugs ones might cause problems), but wouldn't this feature be just a duplication of the above links?

A separate case is our custom checks, which of course should be described better, with examples.

**Comment by rachlenko** [comment]
@krzyk The examples of checkstyle pmd, and findbugs too far from ideal. I know it is a Sisyphean toil to normalize all errors, messages, id's , and examples. We also have to think how to sync it in near future.
If you do not mind to answer to my questions and review my commits , think I could help with this case.

**Comment by rachlenko** [comment]
@yegor256, @krzyk  well , the silent means I've not persuaded anyone :)..

**Comment by krzyk** [comment]
@rachlenko I don't have much time lately, sorry for not responding. As for your idea, I'm afraid that adding such a framework would introduce a lot of maintenance later on.
Also we would be shadowing what Checkstyle/PMD/Findbugs guys are doing in their documentation. I know their documentation is far from perfect, but maybe better approach would be to fix it there?

**Comment by yegor256** [comment]
@rachlenko I'm also not convinced yet... keep in mind that Checkstyle/PMD/FindBugs rules are not static. they do change them, frequently and a lot. we will have to stay in sync with their changes. eventually and inevitably we'll be out of sync. and, there is a bigger concern: what exactly we will add on top of their documentation? if they say that, say, a method without a JavaDoc is a bad thing - what will we add? more examples? what is the value for the end user?

**Comment by rachlenko** [comment]
Thank you . @yegor256  @krzyk.

**Comment by krzyk** [comment]
@rachlenko I think it would be better to have a separate project for such service, when it will exist we could add links from bug descriptions to this service/webpage for hints how to fix errors. Adding such service to qulice itself would make it too complicated and would make it handle to many responsibilities.
If you agree please close this issue and if you have time you could create such service in github and give us a link when it will be ready.

**Comment by krzyk** [comment]
@rachlenko can we close this issue?

**Comment by krzyk** [comment]
@rachlenko ping
