### ISSUE TITLE
Documentation for qulice-gradle-plugin

### ISSUE THREAD

**Issue by jiakuan** [yegor256/qulice#774]
I only saw documentation about how to configure and use qulice with Maven. Are there any documents on how to configure and use gulice with Gradle?

**Comment by krzyk** [comment]
@jiakuan Unfortunately we don't have such documentation yet, thank you for the bug report

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by yegor256** [comment]
dup of #404
