### ISSUE TITLE
Project does not compile in IntelliJ IDEA on Windows

### ISSUE THREAD

**Issue by mkordas** [yegor256/qulice#803]
Whenever I open Qulice on Windows the project does not compile due to missing `com.qulice.spi` dependencies:
![image](https://cloud.githubusercontent.com/assets/5467276/18030388/6c0bfa02-6cb4-11e6-961e-43c71094c7ad.png)
![image](https://cloud.githubusercontent.com/assets/5467276/18030390/8255ef20-6cb4-11e6-8217-747d7573a5c9.png)
Any kind of rebuilding doesn't work.

However, I've noticed that some test pom is recognized by IDEA as `qulice-spi` and it is the root cause of the failure:
![image](https://cloud.githubusercontent.com/assets/5467276/18030394/a2b2962e-6cb4-11e6-943a-fc78cd36c7f2.png)

Let's make sure that this test POM does not interfere with `com.qulice.spi` and it is not recognized as subproject in IDEA.

**Comment by krzyk** [comment]
@mkordas strange, have you done a reimport of the project? Or tried to create it from scratch by ignoring imls and doing import from pom.xml?

**Comment by mkordas** [comment]
@krzyk yes, actually I couldn't compile Qulice on Windows for entire last year trying many things and only recently I've found the root cause - there are two POMs in the project for `qulice-spi`.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else

**Comment by davvd** [comment]
@mkordas thanks for reporting! I topped your account for 15 mins, transaction 57c54e56d3a909024f23de38

**Comment by yegor256** [comment]
@mkordas works good now, on Windows too
