### ISSUE TITLE
INSTALL.txt outdated and other small issues

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/qulice#805]
1) INSTALL.txt needs to be removed as it is completely outdated, written back when svn was used
2) we have to show the number of issues found by each `ResourceValidator`
3) show information about start and finish time of each `ResourceValidator`, similar to what we have for `Validator` and `CheckMojo`

**Comment by krzyk** [comment]
@amihaiemil The whole INSTALL.txt is outdated (it was written when svn was used) so I think it would be best to remove it completely.

**Comment by amihaiemil** [comment]
@krzyk so is this a valid bug, or just cosmetic? :D should i update the desc with what you said?

**Comment by krzyk** [comment]
@amihaiemil rather cosmetic, but we can't add multiple cosmetic ones into a single issue, I've two such issues that you can add to this and it will be a bigger bug report:
* we have to add number of issues found for each `ResourceValidator`
* and also bring back information when each `ResourceValidator` starts and finishes, similar to what we have for `Validator` in `CheckMojo`

**Comment by amihaiemil** [comment]
@krzyk done

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by davvd** [comment]
@amihaiemil thanks for tis bug, I topped your account for 15 mins, transaction `AP-45809960MH275435B`

**Comment by yegor256** [comment]
@amihaiemil I remove this file
