### ISSUE TITLE
Pdd.java:7-7: This is also valid.

### ISSUE THREAD

**Issue by 0pdd** [yegor256/qulice#818]
The puzzle `123-cfed8d02` in `qulice-maven-plugin/src/it/checkstyle-violations/src/main/java/com/qulice/plugin/violations/Pdd.java` (lines 7-7) has to be resolved: This is also valid.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Yegor Bugayenko on 01-Jan-17. 

Estimate: 120 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
@yegor256 please pay attention to this new issue.

**Comment by davvd** [comment]
@krzyk dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)
