### ISSUE TITLE
Pdd.java:24-25: Here we should capture also another line...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/qulice#819]
The puzzle `123-5357374c` in `qulice-maven-plugin/src/it/checkstyle-violations/src/main/java/com/qulice/plugin/violations/Pdd.java` (lines 24-25) has to be resolved: Here we should capture also another line.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Yegor Bugayenko on 01-Jan-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
@yegor256 please pay attention to this new issue.

**Comment by davvd** [comment]
@krzyk please do something about it, see [par.21](http://at.teamed.io/policy.html#21)
