### ISSUE TITLE
XmlValidatorTest.java:91-95: XmlValidator should be able to log IO...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/qulice#829]
The puzzle `246-77de21a5` in [`qulice-xml/src/test/java/com/qulice/xml/XmlValidatorTest.java`](https://github.com/teamed/qulice/blob/master/qulice-xml/src/test/java/com/qulice/xml/XmlValidatorTest.java) (lines 91-95) has to be resolved: XmlValidator should be able to log IO problems (for example, inability to connect to a server) and ignore them (see ticket #243).\ However, {@link com.jcabi.xml.StrictXML} class outright throws an IllegalArgumentException in such cases. Let's find a way to detect whether a failure was caused by such IO errorsand fix this test.

The puzzle was created by unknown on 14-Dec-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue
