### ISSUE TITLE
pom.xml:66-72: This version of jcabi-xml retries if...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/qulice#831]
The puzzle `280-4ce4d8c5` in [`qulice-xml/pom.xml`](https://github.com/teamed/qulice/blob/master/qulice-xml/pom.xml) (lines 66-72) has to be resolved: This version of jcabi-xml retries if the connection to the host of the schema document is reset. However I don't know how to trigger the "connection reset" condition for testing. We should find a way to test whether it does retry if this happens. See issues https://github.com/jcabi/jcabi-xml/issues/32 and https://github.com/teamed/qulice/issues/280 for background details.

The puzzle was created by Carlos Miranda on 12-Jan-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by krzyk** [comment]
@yegor256 0pdd should close this issue some time ago when you removed the qulice-xml module, but it didn't, similar thing with https://github.com/teamed/qulice/issues/835 and https://github.com/teamed/qulice/issues/835

Is there a missing webhook in this repo? I doublechecked and rultor merge script is similar to the one in cactoos where 0pdd closes removed puzzles.
