### ISSUE TITLE
AntEnvironment.java:168-168: Implement exclude and excludes for...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/qulice#834]
The puzzle `337-8e901889` in [`qulice-ant/src/main/java/com/qulice/ant/AntEnvironment.java`](https://github.com/teamed/qulice/blob/master/qulice-ant/src/main/java/com/qulice/ant/AntEnvironment.java) (lines 168-168) has to be resolved: Implement exclude and excludes for ant QuliceTask

The puzzle was created by Yegor Bugayenko on 30-Jun-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue
