### ISSUE TITLE
XmlValidator.java:173-179: Remove the method below and find a...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/qulice#835]
The puzzle `469-1b2c894b` in [`qulice-xml/src/main/java/com/qulice/xml/XmlValidator.java`](https://github.com/teamed/qulice/blob/master/qulice-xml/src/main/java/com/qulice/xml/XmlValidator.java) (lines 173-179) has to be resolved: Remove the method below and find a way to format tags correctly in XML. Attributes should be indented by 4 spaces, just like XML tags, but in IT xml-violations there is a tag that our Prettifier want to be indented by 3 spaces which is wrong. Another problem is that in the parent tag, attributes are indented to match the first attribute, this is also wrong - all attributes on new line should be indented by 4 spaces.

The puzzle was created by krzyk on 17-Oct-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by krzyk** [comment]
@0pdd status
