### ISSUE TITLE
QulicePlugin.java:47-48: Design validator classes for Gradle....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/qulice#839]
The puzzle `339-f214ff2b` in [`qulice-gradle-plugin/src/main/java/com/qulice/gradle/QulicePlugin.java`](https://github.com/teamed/qulice/blob/master/qulice-gradle-plugin/src/main/java/com/qulice/gradle/QulicePlugin.java) (lines 47-48) has to be resolved: Design validator classes for Gradle. And remove the NonStaticMethod exclude below.

The puzzle was created by krzyk on 11-Jan-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue
