### ISSUE TITLE
add clean up command

### ISSUE THREAD

**Issue by ghost** [yegor256/qulice#876]
As per https://github.com/yegor256/cactoos/issues/771 discussion

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ikarsokolov this is out of scope
