### ISSUE TITLE
Qulice doesn't work in projects build with Java 11

### ISSUE THREAD

**Issue by krzyk** [yegor256/qulice#878]
When building a project that uses qulice and the JDK is 11 I get following error:
```
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.17.1:check (jcabi-check) on project cactoos-http: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.17.1:check failed: Plugin com.qulice:qulice-maven-plugin:0.17.1 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.7.0 at specified path /opt/jdk-10/../lib/tools.jar -> [Help 1]
```

This is most probably related to checkstyle - https://github.com/checkstyle/checkstyle/issues/5102

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/878#issuecomment-384931957))

@krzyk Job [#878](https://github.com/teamed/qulice/issues/878) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by longtimeago** [comment]
@krzyk looks like checkstyle introduced java 9 fix with v8.10.1

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@krzyk This problem happened in `0.17.1` version, but does not happens anymore in version `0.18.1`, please take a look at this log:

```
"C:\Program Files\Java\jdk-10.0.2\bin\java.exe" -Dmaven.multiModuleProjectDirectory=C:\git\agamulator -Dmaven.home=C:\apache-maven-3.5.3 -Dclassworlds.conf=C:\apache-maven-3.5.3\bin\m2.conf "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\lib\idea_rt.jar=52356:C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\bin" -Dfile.encoding=UTF-8 -classpath C:\apache-maven-3.5.3\boot\plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2018.2.5 clean install -P jacoco,qulice
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.agamulator:agamulator >----------------------
[INFO] Building agamulator 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ agamulator ---
[INFO] Deleting C:\git\agamulator\target
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.1:prepare-agent (jacoco-initialize) @ agamulator ---
[INFO] argLine set to -javaagent:C:\\Users\\paulo\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.1\\org.jacoco.agent-0.8.1-runtime.jar=destfile=C:\\git\\agamulator\\target\\jacoco.exec,excludes=**/com/agamulator/Main.class:**/com/agamulator/ui/printed/Sysout.class,output=file
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ agamulator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\git\agamulator\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ agamulator ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 57 source files to C:\git\agamulator\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ agamulator ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\git\agamulator\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ agamulator ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 50 source files to C:\git\agamulator\target\test-classes
[WARNING] /C:/git/agamulator/src/test/java/com/agamulator/ui/string/StrPlatformsTest.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/git/agamulator/src/test/java/com/agamulator/ui/string/StrPlatformsTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ agamulator ---
[INFO] Surefire report directory: C:\git\agamulator\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
... lots of tests ...
Results :

Tests run: 79, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.1:check (jacoco-check) @ agamulator ---
[INFO] Loading execution data file C:\git\agamulator\target\jacoco.exec
[INFO] Analyzed bundle 'agamulator' with 33 classes
[INFO] All coverage checks have been met.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.1:report (report) @ agamulator ---
[INFO] Loading execution data file C:\git\agamulator\target\jacoco.exec
[INFO] Analyzed bundle 'agamulator' with 33 classes
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ agamulator ---
[INFO] Building jar: C:\git\agamulator\target\agamulator-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- qulice-maven-plugin:0.18.1:check (default) @ agamulator ---
[INFO] Checkstyle: C:\git\agamulator\src\test\java\com\agamulator\core\db\DatabaseITCase.java[0]: Missing package-info.java file. (JavadocPackageCheck)
[INFO] Checkstyle: C:\git\agamulator\src\test\java\com\agamulator\core\db\DatabaseITCase.java[0]: Problem finding class/interface comment (JavadocTagsCheck)
[INFO] Checkstyle: C:\git\agamulator\src\test\java\com\agamulator\core\db\DatabaseITCase.java[1]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[INFO] Checkstyle: C:\git\agamulator\src\test\java\com\agamulator\core\db\DatabaseITCase.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] Checkstyle: C:\git\agamulator\src\test\java\com\agamulator\core\db\DatabaseITCase.java[3]: Missing a Javadoc comment. (JavadocTypeCheck)
[INFO] Checkstyle: C:\git\agamulator\src\test\java\com\agamulator\core\db\DatabaseITCase.java[4]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.868 s
[INFO] Finished at: 2018-11-30T00:52:20-02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.18.1:check (default) on project agamulator: Failure: There are 6 violations -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

```
Qulice is reporting failed checks

**Comment by paulodamaso** [comment]
@krzyk Mostly looks like `Qulice` does not support due a `findbugs` limitation; as `findbugs` project is discontinued I suggest that we take this java 11 issue after or during https://github.com/teamed/qulice/issues/884 resolution.

**Comment by krzyk** [comment]
@paulodamaso Not only because of findbugs, the hardest problem is with the jcabi-parent, which uses some plugins/dependencies that fail with java >= 9.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@krzyk At the moment `FindBugs` is displaying this nasty stacktrace, so I think it's better to take on this one after we totally replace `FindBugs` by `SpotBugs` because we can assure that the latter will work with java 11 as well

**Comment by paulodamaso** [comment]
@0crat wait for end of https://github.com/teamed/qulice/issues/884 thread

**Comment by 0crat** [comment]
> @0crat wait for end of https://github.com/teamed/qulice/issues/884 thread ([here](https://github.com/teamed/qulice/issues/878#issuecomment-445061109))

@paulodamaso The impediment for [#878](https://github.com/teamed/qulice/issues/878) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
> @0crat wait for resolution of https://github.com/teamed/qulice/issues/959 ([here](https://github.com/teamed/qulice/issues/878#issuecomment-450172283))

@paulodamaso Job [#878](https://github.com/teamed/qulice/issues/878) is already on hold

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/teamed/qulice/issues/878#issuecomment-458096240))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#878](https://github.com/teamed/qulice/issues/878), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#878](https://github.com/teamed/qulice/issues/878); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by fabriciofx** [comment]
@krzyk @gsnoff @andreoss can you confirm if this bug is still open?

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@510b97f6-cc38-487a-9457-d4663bddabf3, thread: pool-220-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'yegor256/qulice' repo was not found
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/qulice#878, Comment: 384931957

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@510b97f6-cc38-487a-9457-d4663bddabf3, thread: pool-221-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'yegor256/qulice' repo was not found
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/qulice#878, Comment: 445061109

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@510b97f6-cc38-487a-9457-d4663bddabf3, thread: pool-223-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'yegor256/qulice' repo was not found
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/qulice#878, Comment: 450172283

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@510b97f6-cc38-487a-9457-d4663bddabf3, thread: pool-224-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'yegor256/qulice' repo was not found
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/qulice#878, Comment: 458096240

**Comment by yegor256** [comment]
@krzyk works fine now, try 0.23.0
