### ISSUE TITLE
Error at line 0: Got an exception - java.lang.NullPointerException (TreeWalker)

### ISSUE THREAD

**Issue by llorllale** [yegor256/qulice#899]
See the build log [here](https://travis-ci.org/yegor256/s3auth/builds/378859685?utm_source=github_status&utm_medium=notification). I've seen a couple of similar issues here as well as [these checks](https://github.com/teamed/qulice/search?utf8=%E2%9C%93&q=nullpointerexception&type=) but I can't figure out the exact cause of the error:

```
[ERROR] /src/main/java/com/s3auth/hosts/Htpasswd.java[0]: Got an exception - java.lang.NullPointerException (TreeWalker)
```

You can find the project [here](https://github.com/llorllale/s3auth/tree/371). 

What's wrong?

**Comment by krzyk** [comment]
@llorllale I think you'll need to update to a newer qulice version, the one in the builds is 0.12, while the newest is 0.17.x
I think this was fixed somewhere around 0.14-0.15 (see https://github.com/teamed/qulice/issues/608)
