### ISSUE TITLE
Let's include SonarLint checks

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/qulice#900]
[SonarLint](https://www.sonarlint.org/) has interesting checks for the Java code. Would will be nice include these checks to Qulice.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@fabriciofx Do you know if there is a maven plugin that uses it already? SonarLint looks more like a IDE plugin, I'm not sure if it has good bindings for CLI tools.

**Comment by fabriciofx** [comment]
@krzyk I'm sorry. I mean [SonarQube](https://www.sonarqube.org/).

**Comment by yegor256** [comment]
@fabriciofx this is out of scope, sorry
