### ISSUE TITLE
Parameter limit is too small

### ISSUE THREAD

**Issue by pdacostaporto** [yegor256/qulice#929]
Three parameters looks like a very small limit for methods and constructors. I have to bypass the ParameterNumber rule frequently, for example for methods that create database records for tables with more than three fields.

Checkstyles default value, 7, looks like a more convenient limit to me.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@pdacostaporto we believe, the smaller the better :)
