### ISSUE TITLE
Share the recommended IDE code style formatting settings

### ISSUE THREAD

**Issue by denis-konovalyenko** [yegor256/qulice#931]
It is really time-consuming to get on with all qulice checks as some of them do go in the other way my default IDE (IntelliJ IDEA) code style formatting settings apply.

Would it be possible to provide (document) links to available resources if there are such (preferably for the IntelliJ IDEA)? This should speed up new-starters and save a bit of time for veterans.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@denis-konovalyenko You could get settings.jar that Yegor uses: https://www.yegor256.com/2017/06/27/my-environment.html at least for now

**Comment by denis-konovalyenko** [comment]
@krzyk , thanks a lot!
