### ISSUE TITLE
Qulice checks reports

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/qulice#937]
I can't generate checkstyle, PMD or findbugs reports on qulice execution. Is there some way of doing this? I'm planning to load these reports on some CI tools and it would be nice if I could use just only one maven execution for generating all the reports I need.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@paulodamaso You mean like html reports? Not there is no such thing in qulice, the only report is the output during the build.

**Comment by krzyk** [comment]
@paulodamaso qulice doesn't generate any report besides the output during build, so there is no way any external tool to work on its output

**Comment by paulodamaso** [comment]
@krzyk I think that ir would be a nice feature to qulice generate these reports, so we don't need to configure and execute every check again to get these reports generated, WDYT?

**Comment by krzyk** [comment]
@paulodamaso Is the format of those reports described somewhere? Is this only for checkstyle or also for PMD and Findbugs?

**Comment by paulodamaso** [comment]
@krzyk I think that these plugins already generate reports someway, but I don't know. If they generate these reports, maybe qulice could use them to generate these reports too. For example, https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html says that checkstyle generates reports on execution, so `qulice-checkstyle` pom could have this `reporting` section so it generates reports for checkstyle executions too. I think that the more reports about the execution better so PMD , Findbugs and other checks should provide them if the plugin allow report generation. But if they don't allow these report generation I think that qulice should not bother with them.

**Comment by krzyk** [comment]
@paulodamaso OK, let's see if that will be doable, should be.

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/937#issuecomment-436200131))

@krzyk Job [#937](https://github.com/teamed/qulice/issues/937) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@krzyk I've made some research on this topic, about `checkstyle` in special, and I've come to some conclusions, they may be helpful:
- checkstyle does not generates any kind of report by itself, it relies on `Apache Maven Checkstyle` plugin to generate them. On the other hand, `qulice` dos not use this plugin for executing checks, so to make these reports accessible qulice should use this plugin to execute `checkstyle` checks; I don't know if this is desirable, though;
- trying to generate the reports re-executing checkstyle plugin (to avoid adding the plugin dependency to qulice) during build did not worked because I couldn't extract qulice configurations for checkstyle to make sure that the same set of rules are used in both builds;

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#937](https://github.com/teamed/qulice/issues/937); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@paulodamaso we don't generate reports. We either fail or pass.
