### ISSUE TITLE
Static imports should be allowed in unit tests

### ISSUE THREAD

**Issue by golszewski86** [yegor256/qulice#945]
Qulice prohibits any static imports. It's good except unit tests which are all use assertions. My favourite assertions framework is AssertJ so I usually write something like:
```
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.Test;
public final class FooTest {
    @Test
    public void shouldReturnBar() {
        assertThat(new Foo().foo()).isEqualTo("bar");
    }
}
```
To please qulice I'd need to write Assertions.assertThat. Repeating Assertions class name only makes my code longer but it doesn't make it better.
- If someone is familiar with AssertJ then they know it's an AssertJ assertion just by looking at the code.
- If someone is not familiar with AssertJ then they would need to look at the documentation anyway
- It's true that reader of this code will need to check what class does the assertThat method come from. But writing Assertions.assertThat doesn't solve the problem because they will need to look what Assertions it is (JUnit, AssertJ or maybe even different)
- In today's world people often use IDEs instead of notepad or vim so it's quite easy to find what the class/method really is.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by golszewski86** [comment]
> Static imports have a very narrow use case
Yes and of these use cases are assertions.

I don't get your second argument however. From the perspective of reviewing code in GitHub, what's the difference between
```
import org.assertj.Assertions;
Assertions.assertThat(bool).isTrue();
```
and
```
import static org.assertj.Assertions.assertThat;
assertThat(bool).isTrue();
```
? In the first case you see what library is used, and in the second you don't?

**Comment by krzyk** [comment]
@golszewski86 Yeah you are right, either way one needs to look at the import. Hmm, I don't have a strong case against assertions.
So you'll be happy if we exclude JUnit, AssertJ and hamcrest (MatcherAssert - this is what most of zerocacy/teamed uses in tests) from the `import static` prohibition?

**Comment by golszewski86** [comment]
I'd be more than happy @krzyk

**Comment by krzyk** [comment]
@yegor256 What do you think? Could we allow assertion libraries to use `import static`, we could limit it to allow:
- `import static org.hamcrest.MatcherAssert.assertThat`
- `import static org.assertj.Assertions.assertThat`

I don't see `assertThat` in JUnit 5 Assertions, so not sure about that, maybe allow also `assertThrows`?

**Comment by golszewski86** [comment]
@krzyk `import static org.assertj.Assertions.assertThatThrownBy` would be also useful

**Comment by dgroup** [comment]
@llorllale this ticket might be interesting for you as the owner of https://github.com/llorllale/cactoos-matchers.
IMHO I don't like this idea with allowing static import for any libraries.
I do believe that it will bloody mess with imports and I don't want to scroll up each time when some assertions are calling.

**Comment by llorllale** [comment]
@dgroup I agree with the OP's sentiment - I also statically import `Matcher#assert` in my personal projects. 

However, as for `cactoos-matchers`, there is still this pending request: llorllale/cactoos-matchers#18

**Comment by llorllale** [comment]
@yegor256 agreed

@golszeski86 btw, `Assertion` has been implemented in `cactoos-matchers` and is useable, although with a couple of pending puzzles open. Try it out if you can.

**Comment by golszewski86** [comment]
> I would stay with "no static import ever" rule...
Any reason for that @yegor256 or it is just "because I say so"?

**Comment by golszewski86** [comment]
@llorllale I'm sorry but the static code analysis tool should not force any particular framework I should work with. There are plenty of them and users should be free to select framework that suits them best, not the one supported by code quality tool.

**Comment by krzyk** [comment]
@golszewski86 qulice is a very specific static analysis tool, preconfigured and opinionated, it is mostly used in projects for teamed and zerocracy

**Comment by dgroup** [comment]
@golszewski86, the qulice doesn't `force you to choose` the particular framework.
The qulice `force you to use` the particular framework `in accordance to` the particular `rules`. The rules defined as a standard, named as `qulice`. 
Why you can't use your static methods with a class name like 
 - MatcherAssert.assertThat
 - Assertions.assertThat

?

For example, when I'm looking at the methods imported by static imports without classes, without `this` reference - for me it is really hard to understand from where this method came.

I disagree with @krzyk that's qulice is a very specific, that's strange statement actually. 
This static analyzer covers the general development approach.

**Comment by krzyk** [comment]
@dgroup no, qulice is not general tool. General tools allow configuration, qulice uses general tools like checkstyle, PMD and configures them according to rules that we want to follow.

**Comment by dgroup** [comment]
@krzyk, but at the same time the qulice allows to suppress the violations from PMD and checkstyle :).

**Comment by krzyk** [comment]
@dgroup because sometimes there are places where you have to cut corners and use PDD to fix that later or there is a bug in qulice or you are forced to do something the way qulice prohibits becasue of library that you are using.

**Comment by dgroup** [comment]
@krzyk, that's true, agree.

**Comment by golszewski86** [comment]
@dgroup 
>  Why you can't use your static methods with a class name like

I can but I don't want to. I simply don't agree it has anything to do with code quality. I only use AssertJ for my tests and my all _assertThat_ methods come from _org.assertj.core.api.Assertions_ class thus it's redundant to repeat the class name everywhere. My code wouldn't be better if I wrote _Assertions.assertThat_ instead of _assertThat_ in each test case.

Moreover, qulice limits line length to 80 characters so every character is precious.

**Comment by yegor256** [comment]
@golszewski86  the decision here: no static imports ever, not even in unit tests.
