### ISSUE TITLE
Let's remove all transient keyword

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/qulice#964]
Although transient keyword was requested to remove still there are some spread around the code. So, let's remove them too.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@fabriciofx this issue is quite small, maybe you can find some more similar issues (or similarly small ones) in the code and update the description?

**Comment by fabriciofx** [comment]
@krzyk Can you list which tickets are handling this issue?

**Comment by krzyk** [comment]
@fabriciofx I'm not sure what you mean. Generally we want to avoid issue reports that results in simple  few line changes, that's why I would either join this issue with another one or think of something else to add to it.

**Comment by yegor256** [comment]
@fabriciofx we don't have them anymore
