### ISSUE TITLE
Let's use maven-verifier-plugin instead of years.sh script

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/qulice#965]
Let's use `maven-verifier-plugin` instead of `years.sh` script to verify correct years information in the copyright header (Cactoos already has been doing it).

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by fabriciofx** [comment]
@krzyk ping
