### ISSUE TITLE
Increase or suppress FileLength checking value

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/qulice#967]
By default Checkstyle's FileLength parameter is set to 2,000 lines of code. Qulice only allow 1,000 lines of code. So, let's update the Qulice value to be equals to Checkstyle or find a way to permit the developer increase this value or suppress this check in your project. Note: I'm not saying to suppress *all* checks in the file code, only suppress this check in a specific file.

**Comment by krzyk** [comment]
@fabriciofx Is there a reason to have a file > 1000 lines?

**Comment by fabriciofx** [comment]
@krzyk ping

**Comment by yegor256** [comment]
@fabriciofx you can just use a normal way to suppress Checkstyle violations
