### ISSUE TITLE
Exclusion comment for RegexpSinglelineCheck doesn't work

### ISSUE THREAD

**Issue by korthout** [yegor256/qulice#976]
Consider the following code:
```java
// @checkstyle RegexpSingleline (1 lines)
final var code = "/** B is a simple class */ class B { }";
```
Running Qulice on it results in the following message:
- `This kind of comment is not allowed. (RegexpSinglelineCheck)`

Line 2 results in a RegexpSinglelineCheck (it shouldn't and is broken, but that is already reported, see #975). Line 1 should exclude the check, but is itself considered conflicting with MethodBodyCommentsCheck and does not exclude the RegexpSinglelineCheck. 

It should be possible to exclude RegexpSinglelineCheck with an exclusion comment.

**Comment by dgroup** [comment]
This rule might be fixed by using `RegexpSinglelineJava`
https://checkstyle.sourceforge.io/config_regexp.html#RegexpSinglelineJava
