### ISSUE TITLE
PMD ConsecutiveLiteralAppends rule makes no sense

### ISSUE THREAD

**Issue by golszewski86** [yegor256/qulice#981]
The following piece of code:
`final StringBuilder sbb = new StringBuilder("A very long text that wouldn't fit one line")`
`.append("Anoher piece of text to append");`

Triggers a PMD warning: _StringBuffer (or StringBuilder).append is called 2 consecutive times with literals. Use a single append with a single combined String. (ConsecutiveLiteralAppends)_

There are some problems with this warning:
- Single combined String wouldn't fit the line length so it will trigger another qulice error
- It is possible to overcome this warning by concatenating strings using String.join but it uses a StringBuilder internally so it's even worse
- One can use String.concat instead but it involves copying an array so it's not better than two appends to the single StriingBuilder
- The reason behind this rule is performance, but typical StringBuilder usage is appending multiple Strings e.g. in a loop so it's very unlikely that there would be a significant performance penalty

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@golszewski86 this is how it should be. In the latest version of Qulice, you can do this:

```
final String sbb = 
  "A very long text that wouldn't fit one line. Anoher piece of text to append";
```

No complain here, no matter how long is the line.
