### ISSUE TITLE
Non-static access to static fields and methods should be prohibited

### ISSUE THREAD

**Issue by golszewski86** [yegor256/qulice#984]
Consider following code:
```
public final class Test {
    private static final String TEXT = "text";

    public void foo() {
        this.bar(this.TEXT);
    }

    private static void bar(final String txt) {
    }
}
```
Static field `TEXT` and static method `bar` should be accessed in static way, but qulice reports no error when they are accessed using `this` keyword.
Java compiler (OpenJDK 1.8.0_191) reports a warning but the code compiles smoothly.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
